support leave and kill
consensus-shipyard/ipc-subnet-actor pull request #8
Opened 2022-11-14 10:00 UTC by cryptoAtwill

## Changes

- Add `leave` and `kill` subnet methods
- Migrate test cases

## Tests

```
cargo test
```

2022-11-15 09:49 UTC, adlrocha requested changes
Just a slight bug in how `mutate_state` is used, but let get it fixed and move to the next one. Thanks!

2022-11-15 09:49 UTC, adlrocha commented on src/lib.rs
> +            st.mutate_state(&TokenAmount::zero());
This is not correct. `mutate_state` expect the current balance of the actor to check if there is some circulating supply pending and staked in the actor balance before we kill it (as after that there is no way of recovering the funds). We should use `rt.curr_balance()` as an argument here.

2022-11-15 09:49 UTC, adlrocha commented on src/lib.rs
> +            st.mutate_state(&TokenAmount::zero());
Same here, we should use `TokenAmoun::zero()`, we should use `rt.curr_balance()`

2022-11-15 09:59 UTC, cryptoAtwill commented on src/lib.rs
> +#![feature(is_some_and)]
it's because I used `Option::is_some_and` and it's rust experimental feature. Maybe I should remove `is_some_and`?

2022-11-15 10:10 UTC, cryptoAtwill commented on src/lib.rs
> +        // TODO: shall we check caller interface instead here?
Looks like the code in transaction performs the check, I'll just remove this section

2022-11-15 10:40 UTC, adlrocha commented on src/lib.rs
> +#![feature(is_some_and)]
Gotcha! This means that we need to use `nightly` then? You can leave it, I was just wondering why explicitly adding it as a feature. Thanks!

2022-11-16 10:35 UTC, adlrocha approved these changes
Let's resolve the last few things that I mentioned and feel free to merge. Thanks!

2022-11-17 13:09 UTC, merged